<a href="https://colab.research.google.com/github/priyadash531/DMDW_LAB_PROGRAM/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Download a dataset from kaggle and upload it in jupyter notebook or google colab. Perform any random operation on the dataset.¶

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files  
uploaded = files.upload()

Saving cars.csv to cars (1).csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['cars.csv']))
df

Unnamed: 0   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  ...  18.60   1   1     4     2

[32 rows x 12 columns]


2)
A) Defining three random arrays: a one-dimensional (x1),two-dimensional (x2) and three-dimensional array(x3). Use NumPy’s random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run.
B) Display the ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array) of the third array (x3).**¶**

In [ ]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


3) Create two numpy arrays named X and Y of integers using range (1-10) and (11-20) command. Next, create a new array Z by concatenate X and Y.¶

In [ ]:
X = np.arange(1,10,dtype = int)
Y = np.arange(11,20,dtype = int)
Z = np.concatenate((X, Y))
print(Z)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


4) Define a two-dimensional (X2). Concatenate X2 with X2.**¶**

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[11,12,13],[14,15,16]])
Z = np.concatenate((X, Y))
print(Z)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


5)
A) Create a numpy array named x of integers using range (1-10) command.
B) Next, perform x+5, x-5, x/5, x*5, x^2, x%2, log(x),log2(x), log10(x) operations over X.
C) Finally, compute some trigonometric functions (sin, cos,tan) on X.¶

In [6]:
X = np.arange(1,10,dtype = int)
print("X+5: ",X+5)
X = np.arange(1,10,dtype = int)
print("X-5: ",X-5)
X = np.arange(1,10,dtype = int)
print("X/5: ",X/5)
X = np.arange(1,10,dtype = int)
print("X*5: ",X*5)
X = np.arange(1,10,dtype = int)
print("X^2: ",np.power(X, 2))
X = np.arange(1,10,dtype = int)
print("X%2: ",np.mod(X,2))
X = np.arange(1,10,dtype = int)
print("log(X): ", np.log(X))
X = np.arange(1,10,dtype = int)
print("log2(X): ", np.log2(X))
X = np.arange(1,10,dtype = int)
print("log10(X): ", np.log10(X))
X = np.arange(1,10,dtype = int)
print("sin: ",np.sin(X))
X = np.arange(1,10,dtype = int)
print("cos: ",np.cos(X))
X = np.arange(1,10,dtype = int)
print("tan: ",np.tan(X))

X+5:  [ 6  7  8  9 10 11 12 13 14]
X-5:  [-4 -3 -2 -1  0  1  2  3  4]
X/5:  [0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
X*5:  [ 5 10 15 20 25 30 35 40 45]
X^2:  [ 1  4  9 16 25 36 49 64 81]
X%2:  [1 0 1 0 1 0 1 0 1]
log(X):  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
log2(X):  [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
log10(X):  [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
tan:  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
