<a href="https://colab.research.google.com/github/priyadash531/DMDW_LAB_PROGRAM/blob/main/class_3_numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 D array
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#2D array

import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a)
b=np.array(([1,2],[3,4]))
print(b)
print(b.shape)
print(a.shape)
b=np.ones((4,3))
print(b)

<class 'numpy.ndarray'>
[1 2 3]
[[1 2]
 [3 4]]
(2, 2)
(3,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
a=np.random.random((3,3))
print(a)
I=np.eye(3)
print(I)


[[0.08749301 0.82981016 0.4864038 ]
 [0.13210117 0.55511287 0.81620364]
 [0.40795776 0.65548021 0.93544724]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
a=np.arange(20)
print(a)
print(a[1:7:2])
print(a[5:15:3])
print(a[-1:5:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5]
[ 5  8 11 14]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6]


In [ ]:
import numpy as np
a=np.array([[12,11],[9,7],[5,13]])
print(a.shape)
print(a>10)

(3, 2)
[[ True  True]
 [False False]
 [False  True]]


In [ ]:
#numpy array mathematics

import numpy as np
a=np.array([[12,11],[9,7],[5,13]])
b=np.random.random((3,2))
print(b)
print(a+b)
print(a-b)
x=np.sum(a)
print(x)
#0----rowwise 1---column wise
y=np.sum(a,axis=0)
print(y)
z=np.sum(a,axis=1)
print(z)

print("----------------------------------")
#TRANSPOSE
print(a)
print("------------")
print(a.T)

#w1x1+w2x2+w3x3=y x is th value and y is the prediction

[[0.62053807 0.35434383]
 [0.44896973 0.4838042 ]
 [0.54873946 0.65868434]]
[[12.62053807 11.35434383]
 [ 9.44896973  7.4838042 ]
 [ 5.54873946 13.65868434]]
[[11.37946193 10.64565617]
 [ 8.55103027  6.5161958 ]
 [ 4.45126054 12.34131566]]
57
[26 31]
[23 16 18]
----------------------------------
[[12 11]
 [ 9  7]
 [ 5 13]]
------------
[[12  9  5]
 [11  7 13]]


In [ ]:
#w1x1+w2x2+w3x3=y x is th value and y is the prediction
#Iris data conatins 4 attribute 
import numpy as np
a=np.array([[12,11,15],[9,7,3]])
print(a)
w=np.array([1.0,1.1])
print(w)
#print(a+w)
#print(a*w)
print((a.T + w).T)



[[12 11 15]
 [ 9  7  3]]
[1.  1.1]
[[13.  12.  16. ]
 [10.1  8.1  4.1]]


In [ ]:
#cOMPLICATED OPERATIONS
import numpy as np



1.Minimax normalization for iris data by using 4 attributes
2